# SPDX-License-Identifier: MIT-0
---
- name: Remove application container
  docker_container:
    name: "{{ web_app_container_name }}"
    state: absent
    force_kill: yes
  when: web_app_full_wipe | bool
  tags:
    - wipe

- name: Remove Docker image
  docker_image:
    name: "{{ web_app_image }}:{{ web_app_image_tag }}"
    state: absent
  when: web_app_full_wipe | bool
  tags:
    - wipe

- name: Clean application files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/opt/{{ web_app_container_name }}"
    - "/var/log/{{ web_app_container_name }}"
  when: web_app_full_wipe | bool
  tags:
    - wipe
